version: '3.4'

services:
  metadocker:
    build:
      context: .
      dockerfile: Dockerfile
    devices:
      - /dev/bus/usb:/dev/bus/usb # change this according to the output of "lsusb | grep -i cypress"
    stdin_open: true
    ports:
      - 5920:5920
    environment:
     - DISPLAY=${DISPLAY}
     - QT_X11_NO_MITSHM=1
     - ROS_DOMAIN_ID=15
    cap_add:
      - SYS_NICE
    network_mode: "host"
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ../..:/workspaces:cached
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - /dev:/dev
    ulimits:
      rtprio: 99
      rttime: -1 # corresponds to 'unlimited'
      memlock: 8428281856